name: net_cliente
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.0+2

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

dependencies:
  dio: ^3.0.10
  flutter_launcher_icons: "^0.8.0"
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  firebase_auth: ^0.18.4+1
  firebase_dynamic_links: ^0.6.3
  cupertino_icons: ^1.0.0
  flutter_native_image: ^0.0.5+3
  firebase_core: ^0.5.3
  firebase_storage: ^5.2.0
  image_picker: ^0.6.7+17
  flutter_svg_provider: ^0.1.7
  image_cropper: ^1.3.1
  flushbar: ^1.10.4
  hasura_connect: ^1.2.2+1
  get_storage: ^1.4.0
  carousel_slider: ^2.3.1
  cached_network_image: ^2.5.0
  url_launcher: ^5.7.10
  mask_shifter: ^0.1.0
  connection_verify: ^1.0.4
  checkbox_formfield: ^0.1.0+3
  flutter_markdown: ^0.5.1
  google_maps_flutter: ^1.0.6
  geolocator: ^6.1.13
  uuid: ^2.2.2
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.3
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo-totem.png
    - assets/images/logo-totem-cinza.png
    - assets/images/splash-image.jpg
    - assets/images/icons-social/zap.svg
    - assets/images/icons-social/instagram.svg
    - assets/images/icons-social/call.svg
    - assets/images/icons-social/email.svg
    - assets/images/icons-social/zap-vazio.svg
    - assets/images/icons-social/instagram-vazio.svg
    - assets/images/icons-social/call-vazio.svg
    - assets/images/icons-social/email-vazio.svg
    - assets/flare/searching.flr
    - assets/md_files/termos_de_uso.md
    - assets/md_files/politica_de_privacidade.md
    - assets/images/logo-totem.png
    - assets/images/noeusebiotem.png
    - assets/images/home-capa.jpg
    - assets/images/home-capa.png
    - assets/images/requisitos.png
    - assets/images/orcamento.png
    - assets/images/desenvolvimento.png
    - assets/images/teste.png
    - assets/images/lancamento.png
    - assets/images/wpp-icon.png
    - assets/images/imagens-perfil/capa.png
    - assets/images/imagens-perfil/capa-negocios.png
    - assets/images/imagens-perfil/perfil.png
    - assets/images/imagens-perfil/perfil-negocios.png
    - assets/images/imagens-perfil/profile.png
    - assets/images/home/lojas.png
    - assets/images/home/restaurantes.png
    - assets/images/home/servicos.png
    - assets/images/home/ongs.png
    - assets/images/home/lojas-cinza.png
    - assets/images/home/restaurantes-cinza.png
    - assets/icon/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Bold.ttf
            weight: 900
          - asset: assets/fonts/Montserrat-BoldItalic.ttf
            weight: 900
            style: italic
          - asset: assets/fonts/Montserrat-Medium.ttf
            weight: 500
          - asset: assets/fonts/Montserrat-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/Montserrat-Regular.ttf
            weight: 400
          - asset: assets/fonts/Montserrat-Italic.ttf
            weight: 400
            style: italic   
          - asset: assets/fonts/Montserrat-Light.ttf
            weight: 300
          - asset: assets/fonts/Montserrat-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/Montserrat-Thin.ttf
            weight: 200
          - asset: assets/fonts/Montserrat-ThinItalic.ttf
            weight: 200
            style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
